config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => "",
    :path_names =>  {:sign_in => "connexion", :sign_out => "logout"},
    controllers: {sessions: 'sessions'}
  root 'pages#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :grilles do 
    collection do 
      post 'import' => 'grilles#import'
     
    end
  end

  get '/supp' => 'grilles#supp'

  resources :emplois do 
    collection do 
      post 'import' => 'emplois#import'
     
    end
  end

  resources :reclassements do 
    collection do 
      post 'import' => 'reclassements#import'
      post 'import_emploi' => 'reclassements#import_emploi'
     
    end
  end

  resources :grades do 
    collection do 
      post 'import' => 'grades#import'
     
    end
  end
  resources :niveaus do 
    collection do 
      post 'import' => 'niveaus#import'
     
    end
  end

  post 'search_grilles', to: 'grilles#search_grilles'

  #get '/hg2et5zbk05ea', to: 'pages#index'
  get '/simulateur', to: 'pages#index'

  get '/mentions-legales', to: 'pages#mentions_legales'
  get '/donnees-personnelles', to: 'pages#donnees_personnelles'
  get '/accessibilite', to: 'pages#accessibilite'
  get '/plan-du-site', to: 'pages#plan'
  post 'select_filter' => 'pages#select_filter'
  post '/select_niveau' => 'pages#select_niveau'
  get '/simulation-impossible', to: 'pages#error_500'
  get '/*path', to: 'pages#error_404'
  match "/404", to: 'pages#error_404', via: :all
  match "/500", to: 'pages#error_500', via: :all

end

app/models/reclassement.rb
class Reclassement < ApplicationRecord

	require 'roo'
  	require 'axlsx'

  	def self.import(file)

  		Reclassement.destroy_all

	  	data = Roo::Spreadsheet.open(file.path)
	    headers = data.row(1) # get header row

	  	data.each_with_index do |row, idx|
	    	next if idx == 0 # skip header
	      	row_data = Hash[[headers, row].transpose]
	      
	        if !row_data["IM"].nil? && !row_data["IM"].blank? #on verifie que la colonne existe 

	            @reclassement = Reclassement.new 
	            @reclassement.echelon = row_data["Echelon"].to_i          
	            @reclassement.indice = row_data["IM"].to_i
	            @reclassement.grade = row_data["Grade"].to_f
	            @reclassement.mois = row_data["Mois"].to_i
	           	@reclassement.save
	            
	        end
		end
	end 
end

app/controllers/reclassements_controller.rb
class ReclassementsController < ApplicationController
	before_action :authenticate_user!
	protect_from_forgery with: :null_session

	def index 
	end 

	def import
		Reclassement.import(params[:file])

	  	respond_to do |format|
		  	format.turbo_stream {redirect_to root_path} 
		end
	end

	def import_emploi
		ReclassementEmploi.import(params[:file])

	  	respond_to do |format|
		  	format.turbo_stream {redirect_to root_path} 
		end
	end
end

app/helpers/reclassements_helper.rb
module ReclassementsHelper
end

app/views/reclassements/index.html.erb
<main role="main" class="containtAll">
  <div class="fr-container fr-mt-7w">
    <div class="fr-col-lg-10 fr-col-offset-lg-1">
      <h1>Ajouter un nouveau document</h1>
      <div class="d24"></div>

     <div>
      <%= form_tag import_reclassements_path, multipart: true do %>
        <div>
          <label><%= file_field_tag  :file, accept: '.xlsx' %>
          </label>
          <div class="d24"></div> 
          <div>
            <%= submit_tag "Transmettre", class:"fr-btn" %>  
          </div>
                    
        </div>
        <% end %>
    </div>
   
    <div class="fr-my-4w"><%= Reclassement.all.count%> données de reclassement</div>
    <h2>Reclassement emplois</h2>
    <div>
      <%= form_tag import_emploi_reclassements_path, multipart: true do %>
        <div>
          <label><%= file_field_tag  :file, accept: '.xlsx' %>
          </label>
          <div class="d24"></div> 
          <div>
            <%= submit_tag "Transmettre", class:"fr-btn" %>  
          </div>
                    
        </div>
        <% end %>
    </div>
    <div class="fr-my-4w"><%= ReclassementEmploi.all.count%> données de reclassement</div>
</div>
</div>
</main>