config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => "",
    :path_names =>  {:sign_in => "connexion", :sign_out => "logout"},
    controllers: {sessions: 'sessions'}
  root 'pages#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :grilles do 
    collection do 
      post 'import' => 'grilles#import'
     
    end
  end

  get '/supp' => 'grilles#supp'

  resources :emplois do 
    collection do 
      post 'import' => 'emplois#import'
     
    end
  end

  resources :reclassements do 
    collection do 
      post 'import' => 'reclassements#import'
      post 'import_emploi' => 'reclassements#import_emploi'
     
    end
  end

  resources :grades do 
    collection do 
      post 'import' => 'grades#import'
     
    end
  end
  resources :niveaus do 
    collection do 
      post 'import' => 'niveaus#import'
     
    end
  end

  post 'search_grilles', to: 'grilles#search_grilles'

  #get '/hg2et5zbk05ea', to: 'pages#index'
  get '/simulateur', to: 'pages#index'

  get '/mentions-legales', to: 'pages#mentions_legales'
  get '/donnees-personnelles', to: 'pages#donnees_personnelles'
  get '/accessibilite', to: 'pages#accessibilite'
  get '/plan-du-site', to: 'pages#plan'
  post 'select_filter' => 'pages#select_filter'
  post '/select_niveau' => 'pages#select_niveau'
  get '/simulation-impossible', to: 'pages#error_500'
  get '/*path', to: 'pages#error_404'
  match "/404", to: 'pages#error_404', via: :all
  match "/500", to: 'pages#error_500', via: :all

end

app/views/pages/_graphe.html.erb
<hr class="fr-col-xs-12 fr-col-12 fr-my-2w">
<div data-controller="highcharts" data-highcharts-donnees="<%= @liste_indices_annuel %>" data-highcharts-donnees2="<%=@liste_indices2_annuel%>" data-highcharts-donnees3="<%=@liste_indices3_annuel%>" data-highcharts-grades="<%= @array_grade_annuel%>" data-highcharts-grades2="<%= @array_grade_reclasse_annuel%>" data-highcharts-efs="<%= @array_ef_annuel%>" data-highcharts-debutdispo="<%=@graphe_debut_dispo%>" data-highcharts-findispo="<%=@graphe_fin_dispo%>">
	<h2>Simulations graphiques du suivi indiciaire</h2>
	<div data-highcharts-target="canvasElement"></div>

	<hr class="fr-grid-row fr-col-xs-12 fr-col-12 fr-my-2w">
	<div data-highcharts-target="canvasElement2"></div>

</div>
<hr class="fr-grid-row fr-col-xs-12 fr-col-12 fr-my-4w">

app/views/pages/_modal_edit.html.erb
<!-- Modal -->
<div class="modal fade" id="edit" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" data-controller="modal">
	<div class="modal-dialog">
		<div class="modal-content">
		    <div class="modal-header">
		        <h5 class="modal-title" id="exampleModalLabel">Attention !</h5>
		        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" data-modal-target='closeButton'></button>
		    </div>

		    <div class="modal-body">
		    	<div class="">Si vous modifiez une caractéristique de votre emploi fonctionnel actuel, vous devrez recommencer les simulations futures.</div>

		    	
		    </div>
			
		      
		</div>
	</div>
</div>
		

app/views/pages/_table.html.erb
<div>
	<h2>Tableau mensuel du suivi indiciaire</h2>
	<div class="fr-table fr-table--layout-fixed">
	    <table>
	    	<thead>
	            <tr>
	                <th scope="col">Date</th>
	                <th scope="col">Indice avant réforme </th>
	                <th scope="col">Indice après réforme sans opter </th>
	                <th scope="col">Indice après réforme en optant</th>
	                <th scope="col">Grade</th>
	                <th scope="col">Grade après réforme en optant</th>
	                <th scope="col">Emploi fonctionnel</th>
	            </tr>
	        </thead>
	        <tbody>
				<% @liste_indices.each_with_index do |indice,i| %>
				<tr>
					<td>1er <%= l(Date.new(2023,1,1) + i.months,format: "%B %Y") %></td>
					<td><%= indice.to_i%></td>
					<td><% if @liste_indices2[i].to_i == 0 %> / <%else%><%= @liste_indices2[i].to_i%><%end%></td>
					<td><%= @liste_indices3[i].to_i%></td>
					<td><%= @array_grade[i]%></td>
					<td><% if @array_grade_reclasse[i]%1 != 0 %>Transitoire<%else%><%= @array_grade_reclasse[i].to_i%><%end%></td>
					<td><%= @array_ef[i]%></td>
				</tr>
				<% end %>
			</tbody>
		</table>

	</div>
	<hr class="fr-grid-row fr-col-xs-12 fr-col-12 fr-my-2w">
</div>

app/views/pages/accessibilite.html.erb
<% content_for :title do %>Accessibilité - SIMULAE <% end %>
<main role="main" class="fr-container fr-py-16v">
<div class="fr-grid-row">
	<div class="fr-col-12 fr-col-md-8">
		  		<h1>Déclaration d'accessibilité</h1>
		  	
				<section class="fr-pb-6v">
					<p class="fr-mt-4v fr-mb-0">La DGAFP s’engage à rendre ses sites internet, intranet, extranet et ses progiciels accessibles (et ses applications mobiles et mobilier urbain numérique) conformément à l’article 47 de la loi n°2005-102 du 11 février 2005.</p>

					<p class="fr-mt-4v fr-mb-0">Cette déclaration d’accessibilité s’applique à SIMULAE (simulae.finances.gouv.fr.).</p>
				</section>
				<section class="fr-pb-6v">
					<h2 class="fr-h2">État de conformité</h2>
					<p class="fr-mt-4v fr-mb-0">SIMULAE est partiellement conforme avec le référentiel général d’amélioration de l’accessibilité (RGAA), version 4 en raison des non-conformités et des dérogations énumérées ci-dessous. </p>
				</section>
				<section class="fr-pb-6v">
					<h3 class="fr-h3">Résultats des tests</h3>
					<p class="fr-mt-4v fr-mb-0">L’audit de conformité réalisé par Budgetlab révèle que : </p>
					<p class="fr-mt-4v fr-mb-0"><ul><li>95% des critères du RGAA version 4 sont respectés; </li></ul></p>
				</section>
				<section class="fr-pb-6v">
					<h2 class="fr-h2">Contenus non accessibles</h2>	
					<h3 class="fr-h3">Non conformités</h3>		
					<p class="fr-mt-4v fr-mb-0"><ul><li>Dans la page du simulateur, les contenus additionnels apparaissant au survol, à la prise de focus ou à l’activation d’un composant d’interface ne sont pas atteignables au clavier.</li></ul></p>
				</section>
				<section class="fr-pb-6v">
					<h2 class="fr-h2">Établissement de cette déclaration d’accessibilité</h2>			
					<p class="fr-mt-4v fr-mb-0">Cette déclaration a été établie le 10 octobre 2022.</p>
				</section>
				<section class="fr-pb-6v">
					<h3 class="fr-h3">Technologies utilisées pour la réalisation l’audit</h3>
					
					<p class="fr-mt-4v fr-mb-0"><ul><li>HTML5</li><li>CSS</li><li>Wave Evaluation tool</li></ul></p>
				</section>
				<section class="fr-pb-6v">
					<h3 class="fr-h3">Environnement de test</h3>
					<p class="fr-mt-4v fr-mb-0">Les vérifications de restitution de contenus ont été réalisées sur la base de la combinaison fournie par la base de référence du RGAA, avec les versions suivantes :</p>
					<p class="fr-mt-4v fr-mb-0"><ul> <li>Google Chrome</li></ul></p>
				</section>
				<section class="fr-pb-6v">
					<h3 class="fr-h3">Outils pour évaluer l’accessibilité</h3>
					<p class="fr-mt-4v fr-mb-0"><ul> <li>color contrast analyzer</li><li>inspecteur de code</li><li>extension google "Wave evaluation tool"</li></ul></p>
				</section>
				<section class="fr-pb-6v">
					<h3 class="fr-h3">Pages du site ayant fait l’objet de la vérification de conformité</h3>
					<p class="fr-mt-4v fr-mb-0"><ul> <li>page d’accueil : https://simulae.finances.gouv.fr</li><li>page du simulateur : https://simulae.finances.gouv.fr/simulateur</li></ul></p>
				</section>
				<section class="fr-pb-6v">
					<h2 class="fr-h2">Retour d’information et contact</h2>
			
					<p class="fr-mt-4v fr-mb-0">
					Si vous n’arrivez pas à accéder à un contenu ou à un service, vous pouvez contacter les responsables SIMULAE pour être orienté vers une alternative accessible ou obtenir le contenu sous une autre forme.</p>

					<p class="fr-mt-4v fr-mb-0"><ul><li>Envoyer un mail à l’adresse : budget.lab@finances.gouv.fr</li><li>Contacter BudgetLab : Ministère de l’Economie, des Finances et de la Souveraineté Industrielle et Numérique, 139 rue de Bercy, 75012 PARIS.</li></ul></p>
				</section>
				<section class="fr-pb-6v">
				<h2 class="fr-h2">Voie de recours</h2>

				<p class="fr-mt-4v fr-mb-0">
					Si vous constatez un défaut d’accessibilité vous empêchant d’accéder à un contenu ou une fonctionnalité du site, que vous nous le signalez et que vous ne parvenez pas à obtenir une réponse de notre part, vous êtes en droit de faire parvenir vos doléances ou une demande de saisie au Défenseur des droits.</p>

				<p class="fr-mt-4v fr-mb-0">Plusieurs moyens sont à votre disposition :</p>

				<p class="fr-mt-4v fr-mb-0">	
					<ul> <li><a target="_blank" rel="noopener" href="https://formulaire.defenseurdesdroits.fr/" title="Écrire un message au Défenseur des droits - nouvelle fenêtre">Écrire un message au Défenseur des droits</a></li>
				
					<li><a target="_blank" rel="noopener" href="https://www.defenseurdesdroits.fr/saisir/delegues" title="Contacter le délégué du Défenseur des droits dans votre région - nouvelle fenêtre">Contacter le délégué du Défenseur des droits dans votre région</a>
					</li>
					<li>
					Envoyer un courrier par la poste (gratuit, ne pas mettre de timbre) :
					Défenseur des droits
					Libre réponse 71120 75342 Paris CEDEX 07
		  			</li>
		  			</ul>
		  		</p>
		  		
		  		</section>
	</div>
</div>
</main>

app/views/pages/accueil.html.erb
<% content_for :title do %>Accueil - Simulae <% end %>
<main role="main" class="containtAll">

<div class="fr-container fr-mt-7w">
	<div class="fr-grid-row fr-grid-row--gutters">
		<div class="fr-col-lg-12">
			<h1> SIMULAE, Simulateur de la réforme de la haute fonction publique</h1>
			<p><a class="fr-link" href="/simulateur">Accéder au simulateur <span class="fr-icon-arrow-right-line fr-ml-1v fr-fi--sm" aria-hidden="true"></span></a></p>
				<div class="fr-notice fr-notice--info">
				    <div class="fr-container">
				        <div class="fr-notice__body">
				            <p class="fr-notice__title">
				              Texte de présentation de la réforme et d’utilisation de l’outil à construire par la DGAFP.
				            </p>
				        </div>
				    </div>
				</div>
		</div>

	</div>
</div>
<hr class="fr-grid-row fr-col-xs-10 fr-col-7 fr-my-7w">


<div class="fr-container">
	<div class="fr-grid-row fr-grid-row--gutters">
		<div class="fr-col-lg-12">

			<h2>Questions fréquentes </h2>
			<div class="fr-notice fr-notice--info">
				    <div class="fr-container">
				        <div class="fr-notice__body">
				            <p class="fr-notice__title">
				              À construire par la DGAFP.
				            </p>
				        </div>
				    </div>
				</div>
		</div>

	</div>
</div>
<hr class="fr-grid-row fr-col-xs-10 fr-col-7 fr-my-7w">
<div class="fr-follow">
        <div class="fr-container">
        <div class="fr-grid-row fr-grid-row--gutters fr-grid-row--middle">
            <div class="fr-col-12">
                <div class="fr-follow__newsletter">
                    <div>
                        <h5 class="fr-h5 fr-follow__title">Une question concernant SIMULAE ?</h5>
                        <p class="fr-text--sm fr-follow__desc">Si vous rencontrez un problème dans l'utilisation de l'outil, vous pouvez nous envoyer un mail en cliquant sur le bouton ci-contre.</p>
                    </div>
                    <div>
                       <a href="mailto:budget.lab@finances.gouv.fr?subject=Contact-SIMULAE" class="fr-btn" rel="noopener" target="_blank" title="Nous contacter - nouvelle fenêtre">Nous contacter</a>
                    </div>
                </div>
            </div>
    
        </div>
        </div>
    </div>
</main>

app/views/pages/donnees_personnelles.html.erb
<% content_for :title do %>Données personnelles - Simulae <% end %>
<main role="main" class="fr-container fr-py-16v">
<div class="fr-grid-row">
	<div class="fr-col-12 fr-col-md-8">
		  	<h1>Données Personnelles et Gestion des Cookies </h1>
		  	<section class="fr-py-6v">
		  		<h2 class="fr-h2">Données personnelles</h2>
				<p class="fr-mt-4v fr-mb-0">
					Ce site ne prélève aucune donnée à caractère personnel et ne fait intervenir aucun cookies. 
				</p>
			</section>
			<section class="fr-py-6v fr-hidden">
				<h2 class="fr-h5">Cookies déposés et opt-out</h2>
				<p class="fr-mt-4v fr-mb-0">Ce site dépose un petit fichier texte (un « cookie ») sur votre ordinateur lorsque vous le consultez. Cela nous permet de mesurer le nombre de visites et le type d’interactions faites avec l’outil.</p>
			</section>
			<section class="fr-py-6v">
				<h2 class="fr-h2">Ce site n’affiche pas de bannière de consentement aux cookies, pourquoi ?</h2>
				<p class="fr-mt-4v fr-mb-0">Nous respectons la loi, qui dit que certains outils de suivi d’audience, correctement configurés pour respecter la vie privée, sont exemptés d’autorisation préalable.
				Nous utilisons pour cela <a target="_blank" rel="noopener" href=https://abla.io" title="Aller sur Abla - nouvelle fenêtre">Abla</a>, un outil libre, paramétré pour être en conformité avec la <a target="_blank" rel="noopener" href="https://www.cnil.fr/fr/solutions-pour-la-mesure-daudience" title="Aller sur CNIL - nouvelle fenêtre">recommandation « Cookies » de la CNIL</a>. Cela signifie que votre adresse IP, par exemple, est anonymisée avant d’être enregistrée. Il est donc impossible d’associer vos visites sur ce site à votre personne.</p>
			</section>
		</div>
	</div>
</main>
				
				

app/views/pages/error_404.html.erb
<main role="main" id="content">
                <div class="fr-container">
                    <div class="fr-my-7w fr-mt-md-12w fr-mb-md-10w fr-grid-row fr-grid-row--gutters fr-grid-row--middle">
                        <div class="fr-py-0 fr-col-12 fr-col-md-6 fr-col-offset-md-1">
                            <h1>Page non trouvée</h1>
                            <p class="fr-text--sm fr-mb-3w">Erreur 404</p>
                            <p class="fr-text--lg fr-mb-3w">La page que vous cherchez est introuvable. Excusez-nous pour la gène occasionnée.</p>
                            <p class="fr-text--sm fr-mb-6w">
                                Si vous avez tapé l'adresse web dans le navigateur, vérifiez qu'elle est correcte. La page n’est peut-être plus disponible.
                                <br>Dans ce cas, pour continuer votre visite vous pouvez consulter notre page d’accueil.
                            </p>
                            <ul class="fr-btns-group fr-btns-group--inline-md">
                                <li>
                                    <%= link_to root_path, class:"fr-btn" do %>
                                        Page d'accueil
                                    <%end%>
                                </li>
                            </ul>
                        </div>
                        <div class="fr-col-12 fr-col-md-3 fr-col-offset-md-1 fr-px-6w fr-px-md-0">
                            
                            <%= image_tag "technical-error.svg", class: "fr-responsive-img fr-artwork", height: '200', width: '160' %>
                              
                        </div>
                    </div>
                </div>
            </main>

app/views/pages/error_500.html.erb
<main role="main" id="content">
                <div class="fr-container">
                    <div class="fr-my-7w fr-mt-md-12w fr-mb-md-10w fr-grid-row fr-grid-row--gutters fr-grid-row--middle">
                        <div class="fr-py-0 fr-col-12 fr-col-md-6 fr-col-offset-md-1">
                            <h1>Simulation impossible</h1>
                            <p class="fr-text--sm fr-mb-3w">Erreur</p>
                            <p class="fr-text--lg fr-mb-3w">La simulation est impossible avec les informations renseignées.</p>
                            <p class="fr-text--sm fr-mb-6w">
                                Veuillez recommencez en changeant les caractéristiques.
                                <br>Si vous avez besoin d'une aide immédiate, merci de nous contacter.
                            </p>
                            <ul class="fr-btns-group fr-btns-group--inline-md">
                                <li>
                                    <%= link_to root_path, class:"fr-btn" do %>
                                        Page d'accueil
                                    <%end%>
                                </li>
                                <li>
                                    <a class="fr-btn fr-btn--secondary" href="mailto:declic.budget@finances.gouv.fr" target="_blank">
                                        Contactez-nous
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <div class="fr-col-12 fr-col-md-3 fr-col-offset-md-1 fr-px-6w fr-px-md-0">
                            
                            <%= image_tag "technical-error.svg", class: "fr-responsive-img fr-artwork", height: '200', width: '160' %>
                              
                        </div>
                    </div>
                </div>
            </main>

app/views/pages/index.html.erb
<% content_for :title do %>Effectuez votre simulation - Simulae <% end %>

<main role="main" class="containtAll" >
	<div class="fr-container">
		
		<div class="fr-grid-row fr-grid-row--gutters">
			<div class="fr-col-12 fr-col-lg-12">
				<h1 class="fr-mt-6w"> Simulez votre situation indiciaire future <span class="pright"> <%= link_to simulateur_path, class:" fr-btn fr-btn--icon-left" do %><span class="fr-fi-refresh-line fr-fi--sm fr-mr-1v" aria-hidden="true"></span>Réinitialiser<%end%></span></h1>
				
				<div class="fr-notice fr-notice--info">
				    <div class="fr-container">
				        <div class="fr-notice__body">
				            <p class="fr-notice__title">
				              Tous les champs comportant un astérisque (*) sont à remplir obligatoirement. Lorsqu'une année est renseignée, c'est la date du <u>1er janvier de l'année</u> qui est prise en compte.
				            </p>
				        </div>
				    </div>
				</div>
			</div>
		</div>

	</div>

	<hr class="fr-grid-row fr-col-xs-12 fr-col-12 fr-my-2w">

	<div class="fr-container">
		<% if !@corps.nil? && !@emplois_f2.nil?%>
		<div class="fr-grid-row fr-grid-row--gutters">
			<div class="fr-col-12">
				<%= render 'form'%>
			</div>	
		</div>

		<% end %>
	</div>
</main>

app/views/pages/mentions_legales.html.erb
<% content_for :title do %>Mentions légales - Simulae <% end %>
<main role="main" class="fr-container fr-py-16v">

<div class="fr-grid-row">
	<div class="fr-col-12 fr-col-md-8">
		  		<h1>Mentions légales</h1>
		  	
				<section class="fr-pb-6v">
				
				<p class="fr-mt-4v fr-mb-0">
					Ce site est édité par la Direction du Budget au sein du Ministère de l'Économie, des finances et de la relance. 
				</p>
				<p class="fr-mt-4v fr-mb-0">Les mentions légales ont été établies le 16 Juillet 2022. Elles ont été mises à jour le 5 octobre 2022.</p>
				</section>
				<section class="fr-py-6v">
				<h2 class="fr-h2">Directeur de publication</h2>
				<p class="fr-mt-4v fr-mb-0">Mr Benoît LAROCHE DE ROUSSANE</p>

				</section>
				<section class="fr-py-6v">
				<h2 class="fr-h2">Conception et gestion du site</h2>
				<p class="fr-mt-4v fr-mb-0">Ce site est conçu et développé par l’équipe Budgetlab et utilise le système de design de l’État.</p>

				</section>
				<section class="fr-py-6v">
				<h2 class="fr-h2">Code source du site</h2>
				<p class="fr-mt-4v fr-mb-0">Le code source du site est disponible sur Github.</p>
				</section>
				<section class="fr-py-6v">
				<h2 class="fr-h2">Propriété intellectuelle et liens</h2>
				<p class="fr-mt-4v fr-mb-0">Tout site public ou privé est autorisé à établir, sans autorisation préalable, un lien vers les informations diffusées sur simulae.finances.gouv.fr</p>
				<p class="fr-mt-4v fr-mb-0">Sauf mention de propriété intellectuelle détenue par des tiers, les contenus de ce site sont proposés sous licence ouverte 2.0.</p>
				<p class="fr-mt-4v fr-mb-0">La mise en place de liens vers nos contenus et documents est cependant est à privilégier par rapport à la reproduction sur un site tiers. La mention explicite du site source simulae.finances.gouv.fr est recommandée.</p>
				</section>
				<section class="fr-py-6v">
				<h2 class="fr-h2">Hébergement </h2>
				<p class="fr-mt-4v fr-mb-0">Google Cloud Platform - Google France</p>
				<p class="fr-mt-4v fr-mb-0">Fournisseur de Cloud public (CSP) Google dans le cadre du marché UGAP C3</p>
				<p class="fr-mt-4v fr-mb-0">
					8, rue de Londres, 75009 Paris France
					01 42 68 53 00
				</p>

				</section>
				
				
</div>
</div>

</main>				

app/views/pages/plan.html.erb
<% content_for :title do %>Plan du site - SIMULAE <% end %>
<main role="main" class="fr-container fr-py-16v">
<div class="fr-grid-row">
	<div class="fr-col-12 fr-col-md-8">
		  	<h1>Plan du site </h1>
		  	
			<section class="fr-py-6v">
				<ul>
				
					<li><%= link_to root_path do %>Accueil Simulateur<%end%></li>
					<li><%= link_to plan_du_site_path do %>Plan du site<%end%></li>
					<li><%= link_to accessibilite_path do %>Accessibilité<%end%></li>
					<li><%= link_to mentions_legales_path do %>Mentions légales<%end%></li>
					<li><%= link_to donnees_personnelles_path do %>Données personnelles & Gestion des cookies<%end%></li>	
						
				</ul>
			</section>
		</div>
	</div>
</main>
				
				