config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => "",
    :path_names =>  {:sign_in => "connexion", :sign_out => "logout"},
    controllers: {sessions: 'sessions'}
  root 'pages#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :grilles do 
    collection do 
      post 'import' => 'grilles#import'
     
    end
  end

  get '/supp' => 'grilles#supp'

  resources :emplois do 
    collection do 
      post 'import' => 'emplois#import'
     
    end
  end

  resources :reclassements do 
    collection do 
      post 'import' => 'reclassements#import'
      post 'import_emploi' => 'reclassements#import_emploi'
     
    end
  end

  resources :grades do 
    collection do 
      post 'import' => 'grades#import'
     
    end
  end
  resources :niveaus do 
    collection do 
      post 'import' => 'niveaus#import'
     
    end
  end

  post 'search_grilles', to: 'grilles#search_grilles'

  #get '/hg2et5zbk05ea', to: 'pages#index'
  get '/simulateur', to: 'pages#index'

  get '/mentions-legales', to: 'pages#mentions_legales'
  get '/donnees-personnelles', to: 'pages#donnees_personnelles'
  get '/accessibilite', to: 'pages#accessibilite'
  get '/plan-du-site', to: 'pages#plan'
  post 'select_filter' => 'pages#select_filter'
  post '/select_niveau' => 'pages#select_niveau'
  get '/simulation-impossible', to: 'pages#error_500'
  get '/*path', to: 'pages#error_404'
  match "/404", to: 'pages#error_404', via: :all
  match "/500", to: 'pages#error_500', via: :all

end

app/models/niveau.rb
class Niveau < ApplicationRecord
	require 'roo'
  	require 'axlsx'

  	def self.import(file)
  		Niveau.all.destroy_all
  		
	  	data = Roo::Spreadsheet.open(file.path)
	    headers = data.row(1) # get header row

	  	data.each_with_index do |row, idx|
	    	next if idx == 0 # skip header
	      	row_data = Hash[[headers, row].transpose]
	      
	        if !row_data["Emploi"].nil? && !row_data["Emploi"].blank? #on verifie que la colonne existe 

	            @niveau = Niveau.new 
	            
	            @niveau.emploi = row_data["Emploi"]
	            @niveau.niveau = row_data["Niveau"].to_i  
	            @niveau.save
	            
	        end
		end
	end 
end

app/controllers/niveaus_controller.rb
class NiveausController < ApplicationController
	before_action :authenticate_user!
	def index
	end 
	def import
		
	  	Niveau.import(params[:file])

	  	respond_to do |format|
		  	format.turbo_stream {redirect_to root_path} 
		end
	end
end

app/helpers/niveaus_helper.rb
module NiveausHelper
end

app/views/niveaus/index.html.erb
<main role="main" class="containtAll">
  <div class="fr-container fr-mt-7w">
    <div class="fr-col-lg-10 fr-col-offset-lg-1">
      <h1>Ajouter un nouveau document</h1>
      <div class="d24"></div>

     <div>
      <%= form_tag import_niveaus_path, multipart: true do %>
        <div>
          <label><%= file_field_tag  :file, accept: '.xlsx' %>
          </label>
    
          <div class="d24"></div> 
          <div>
            <%= submit_tag "Transmettre", id: "submit_btn", class:"fr-btn" %>  
          </div>
                    
        </div>
        <% end %>
  </div>
  <div class="d24"></div>
  <div><%= Niveau.all.count%> données</div>
</div>
</div>
</main>